services:
  pzserver-manager:
    build: .
    container_name: webapp
    ports:
      - "5000:5000"
    volumes:
      # Mount source code for live editing
      # Mount source code for live editing
      - ./run.py:/app/run.py
      - ./app:/app/app
      - ./templates:/app/templates
      - ./static:/app/static
      # Mount mock data to persist changes
    environment:
      - PZ_ENV=local